Adds serializers for User Profile & unit tests for the serializers
sametimesameplace/backend pull request #20
Opened 2023-11-08 12:07 UTC by SteffenDCI

Hi,

please review the pull request. 
The code is still under construction but I didn't want to fall behind with code commits.

2023-11-08 13:05 UTC, Termuellinator requested changes
Nice work with a few things that need a bit of tweaking :)

2023-11-08 13:05 UTC, Termuellinator commented on apps/user/serializers.py
> +from .models import UserProfile
as you already import models in line 5, this is redundant

2023-11-08 13:05 UTC, Termuellinator commented on apps/user/serializers.py
> +    def validate_email(self, value):
This should be part of the `AbstractUser` i think? But we need something like that for the UserProfile email field. Might also be a non-issue though as it might be taken care of by the fact that it's an email field in the model.

2023-11-08 13:05 UTC, Termuellinator commented on apps/user/serializers.py
> +    def validate_phone(self, value):
Probably a mix up - the phone number is in the UserProfile model.

2023-11-08 13:05 UTC, Termuellinator commented on apps/user/serializers.py
> +            "languages"
i think the languages have to be passed through the UserLanguageSerializer?

2023-11-08 13:05 UTC, Termuellinator commented on apps/user/serializers.py
> +            "user",
I think the user shouldn't be set manually but automatically by the request.user (see TimePlace view)

2023-11-08 13:05 UTC, Termuellinator commented on apps/user/serializers.py
> +            "user",
I think the user shouldn't be set manually but automatically by the request.user (see TimePlace view)

2023-11-08 13:05 UTC, Termuellinator commented on apps/user/serializers.py
> +            "languages"
i think the languages have to be passed through the UserLanguageSerializer?

2023-11-08 13:05 UTC, Termuellinator commented on apps/user/serializers.py
> +            "user",
User should be passed through the UserSerializer i'd say. Or we include the UserProfile in the UserSerializer and just have the user id here.

2023-11-08 13:05 UTC, Termuellinator commented on apps/user/serializers.py
> +            "age",
age still has to be calculated somewhere, doesn't it?

2023-11-08 13:05 UTC, Termuellinator commented on apps/user/serializers.py
> +            "languages"
i think the languages should be passed through the UserLanguageSerializer here as well. Otherwise, we'd only get a list of IDs back and the frontend would have to make requests for each language separately.

2023-11-08 13:05 UTC, Termuellinator commented on apps/user/tests/ut/test_user.py
> +    def test_invalid_serializer_data_update(self):
according to the function name, this should test invalid data ;)

2023-11-08 13:05 UTC, Termuellinator commented on apps/user/views.py
> +    ]
This way, all methods for the viewset would use the `UserProfileRetrieveSerializer`.
The best solution i found was to overwrite the `get_serializer_class` method.

2023-11-09 15:38 UTC, Termuellinator commented
Uhm, something seems to have gone wrong, your PR no has several commits that have already been merged. Let's talk about this tomorrow!

2023-11-10 09:07 UTC, SteffenDCI commented
Let's try a new pull request, because I rebased the steffen-dev branch after making the original PR

2023-11-10 09:07 UTC, closed without merging